print('---ANTECESSOR E SUCESSOR---')
Numero = int(input('Digite um numero: '))
sucessor = (Numero + 1)
antecessor = (Numero-1)
print('O numero digitado foi {}, seu antecessor e: {}, o seu sucessor e: {}'.format(Numero,antecessor,sucessor))
