print("---Media Ponderada---")
numero1 = int(input("Digite um numero: "))
numero2 = int(input("Digite um numero: "))
numero3 = int(input("Digite um numero: "))
numero4 = int(input("Digite um numero: "))
mediaponderada = (numero1*1+numero2*2+numero3*3+numero4*4)/(1+2+3+4)
print('A media ponderada de {},{},{},{} e {}'.format(numero1,numero2,numero3,numero4,mediaponderada))
